### ISSUE TITLE
Browser outline appears on mobile upon button press

### ISSUE THREAD

**Issue by adalinesimonian** [richiksc/refresh-button#1]
When pressing the button on mobile, the browser outline appears surrounding the button, whereas with paper-icon-button, this is not the case. This obstructs visibility of the ripple and provides redundant touch feedback.

[I uploaded a few screenshots](http://imgur.com/a/Imo3V). The first image displays what is the expected behaviour, and the second two images display what currently happens when pressing the button.

Tested on Moto X XT1097, Android 5.0.2, Chrome 40.0.2214.109, Blink 537.36 (@189407).

**Comment by richiksc** [comment]
Will add `outline: none;`

**Comment by richiksc** [comment]
Fixed. [commit](https://github.com/richiksc/refresh-button/commit/479edc5eea9037bc1c2cf4fc0876a91859391728)
